<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyShipper" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-DFSF0MK1\SQLEXPRESS;Initial Catalog=QuanLyShipper;Integrated Security=True" SettingsObjectName="QuanLyShipper.Properties.Settings" SettingsPropertyName="QuanLyShipperConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ThoiDiemNhan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiDiemNhanHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemNhan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemDen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangDon" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Shipper_DonHang" Member="Shipper" ThisKey="MaSP" OtherKey="MaSP" Type="Shipper" IsForeignKey="true" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="QuanLy_DonHang" Member="QuanLy" ThisKey="MaQL" OtherKey="MaQL" Type="QuanLy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shipper" Member="Shippers">
    <Type Name="Shipper">
      <Column Name="MaSP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SDTSP" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="TaiKhoanNganHang" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TaiKhoanSP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MatKhauSP" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Shipper_DonHang" Member="DonHangs" ThisKey="MaSP" OtherKey="MaSP" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTKH" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="TaiKhoanKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhauKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.QuanLy" Member="QuanLies">
    <Type Name="QuanLy">
      <Column Name="MaQL" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoanQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhauQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QuanLy_DonHang" Member="DonHangs" ThisKey="MaQL" OtherKey="MaQL" Type="DonHang" />
    </Type>
  </Table>
</Database>