//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoanThien.FormChildAdmin.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLMatHang
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string GiaSP { get; set; }
        public string LoaiSP { get; set; }
        public string DiaChi { get; set; }
    }
}
