//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoanThien.FormChildAdmin.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLHangEntities1 : DbContext
    {
        public QLHangEntities1()
            : base("name=QLHangEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QLMatHang> QLMatHangs { get; set; }
    
        public virtual int GetHangOrSearch(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHangOrSearch", queryParameter);
        }
    
        public virtual ObjectResult<SP_Retrieve_User_Result> SP_Retrieve_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Retrieve_User_Result>("SP_Retrieve_User");
        }
    
        public virtual int SP_SuaMatHang(Nullable<int> maSP, string tenSP, string giaSP, string loaiSP, string diaChi)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaSPParameter = giaSP != null ?
                new ObjectParameter("GiaSP", giaSP) :
                new ObjectParameter("GiaSP", typeof(string));
    
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuaMatHang", maSPParameter, tenSPParameter, giaSPParameter, loaiSPParameter, diaChiParameter);
        }
    
        public virtual int SP_ThemMatHang(string tenSP, string giaSP, string loaiSP, string diaChi)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaSPParameter = giaSP != null ?
                new ObjectParameter("GiaSP", giaSP) :
                new ObjectParameter("GiaSP", typeof(string));
    
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemMatHang", tenSPParameter, giaSPParameter, loaiSPParameter, diaChiParameter);
        }
    
        public virtual int SP_XoaMatHang(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XoaMatHang", maSPParameter);
        }
    }
}
